FROM python

ENV gmuser <replace>
ENV gmpass <replace>
ENV azurestoracct <replace>
ENV azurequeue <replace>
ENV azurequeuekey <replace>

RUN pip install requests
RUN pip install azure-storage

RUN mkdir /stock-report && mkdir /tmp-app && \
    git clone https://github.com/neilpeterson/container-stock-app-service.git /tmp-app && \
    cp -rf /tmp-app/python-stock-report/* /stock-report && \
    rm -rf /tmp-app

ENTRYPOINT ["python", "/stock-report/stock-report.py"]