FROM python

ENV gmuser xneilpetersonx@gmail.com
ENV gmpass TempForDemo2016

RUN pip install requests

RUN mkdir /stock-report && mkdir /tmp-app && \
    git clone https://github.com/neilpeterson/container-stock-app-service.git /tmp-app && \
    cp -rf /tmp-app/python-stock-report/* /stock-report && \
    rm -rf /tmp-app

ENTRYPOINT ["python", "/stock-report/stock-report.py"]