FROM windowsservercore

ENV azurestoracct <account>
ENV azurequeue <queue name>
ENV azurequeuekey <queue key>
ENV docker http://<docker host>:2375/containers/
ENV image neilpeterson/stock-report

RUN powershell.exe -Command \
    $ErrorActionPreference = 'Stop'; \
    wget https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe ; \
    Start-Process c:\python-3.5.1.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
    Remove-Item c:\python-3.5.1.exe -Force

RUN pip install requests
RUN pip install azure-storage

RUN powershell -Command \
    mkdir c:\queue-worker ; \
    Invoke-WebRequest -Method Get -Uri "https://raw.githubusercontent.com/neilpeterson/container-stock-app/master/python-stock-back-service/queue-worker.py" -OutFile c:\queue-worker\queue-worker.py

ENTRYPOINT ["python", "/queue-worker/queue-worker.py"]